import typing as t
from pycdp.utils import LoggerMixin as LoggerMixin

class BrowserLauncher(LoggerMixin):
    def __init__(self, *, binary: str, profile: t.Optional[str] = None, keep_profile: bool = True, headless: bool = False, locale: t.Optional[str] = None, timezone: t.Optional[str] = None, proxy: t.Optional[str] = None, window_width: t.Optional[int] = None, window_height: t.Optional[int] = None, initial_url: t.Optional[str] = None, extensions: t.List[str] = [], args: t.Optional[t.List[str]] = None, log: bool = True) -> None: ...
    @property
    def pid(self) -> int: ...
    @property
    def locale(self): ...
    @property
    def timezone(self): ...
    def launch(self) -> None: ...
    def kill(self, timeout: float = 3.0): ...
    def __del__(self) -> None: ...

class ChromeLauncher(BrowserLauncher): ...
