from _typeshed import Incomplete

__all__ = ['install_optimal_reactor', 'install_reactor', 'current_reactor_klass']

def current_reactor_klass(): ...
def install_optimal_reactor(require_optimal_reactor: bool = True): ...
def install_reactor(explicit_reactor: Incomplete | None = None, verbose: bool = False, log: Incomplete | None = None, require_optimal_reactor: bool = True): ...
