[tool.mypy]
python_version = "3.9"
plugins = ["mypy_zope:plugin"]
mypy_path = "./external_stubs/"
warn_return_any = true
warn_unused_configs = true
disallow_any_unimported = true
disallow_any_decorated = true
#disallow_any_explicit = true
#disallow_any_generics = true
disallow_subclassing_any = true
disallow_untyped_calls = true

disallow_untyped_defs = true
disallow_incomplete_defs = true

check_untyped_defs = true
disallow_untyped_decorators = true
warn_unused_ignores = true
warn_unreachable = true

namespace_packages = true

[[tool.mypy.overrides]]
module = "pycdp.*"
ignore_missing_imports = true
disallow_any_unimported = false
disallow_untyped_defs = false
disallow_incomplete_defs = false

[[tool.mypy.overrides]]
module = "autobahn.*"
disallow_untyped_defs = false
disallow_incomplete_defs = false

[[tool.mypy.overrides]]
module = "adblockparser.*"
disallow_untyped_defs = false
disallow_incomplete_defs = false

[tool.pylint.main]
fail-under = 9

[tool.pylint."messages control"]
disable = ["missing-function-docstring", "missing-class-docstring"]

[tool.pylint.format]
max-line-length = 120
