def test_primitive_type() -> None: ...
def test_enum_type() -> None: ...
def test_class_type() -> None: ...
def test_event_type() -> None: ...
def test_event_type_with_dependency() -> None: ...
def test_event_dispatch() -> None: ...
