from autobahn.wamp.types import RegisterOptions, SubscribeOptions
from typing import Optional, Union

__all__ = ['Pattern', 'register', 'subscribe', 'error', 'convert_starred_uri']

def convert_starred_uri(uri: str): ...

class Pattern:
    URI_TARGET_ENDPOINT: int
    URI_TARGET_HANDLER: int
    URI_TARGET_EXCEPTION: int
    URI_TYPE_EXACT: int
    URI_TYPE_PREFIX: int
    URI_TYPE_WILDCARD: int
    def __init__(self, uri: str, target: int, options: Optional[Union[SubscribeOptions, RegisterOptions]] = None, check_types: Optional[bool] = None) -> None: ...
    @property
    def options(self): ...
    @property
    def uri_type(self): ...
    def uri(self): ...
    def match(self, uri): ...
    def is_endpoint(self): ...
    def is_handler(self): ...
    def is_exception(self): ...

def register(uri: Optional[str], options: Optional[RegisterOptions] = None, check_types: Optional[bool] = None): ...
def subscribe(uri: Optional[str], options: Optional[SubscribeOptions] = None, check_types: Optional[bool] = None): ...
def error(uri: str): ...
