__all__ = ['PerMessageCompressOffer', 'PerMessageCompressOfferAccept', 'PerMessageCompressResponse', 'PerMessageCompressResponseAccept', 'PerMessageCompress']

class PerMessageCompressOffer: ...
class PerMessageCompressOfferAccept: ...
class PerMessageCompressResponse: ...
class PerMessageCompressResponseAccept: ...
class PerMessageCompress: ...
