from wsaccel.utf8validator import Utf8Validator as Utf8Validator

__all__ = ['Utf8Validator']

class Utf8Validator:
    def __init__(self) -> None: ...
    def decode(self, b): ...
    def reset(self) -> None: ...
    def validate(self, ba): ...
