import typing
from . import dom as dom, runtime as runtime
from .util import T_JSON_DICT as T_JSON_DICT, event_class as event_class
from dataclasses import dataclass

@dataclass
class Animation:
    id_: str
    name: str
    paused_state: bool
    play_state: str
    playback_rate: float
    start_time: float
    current_time: float
    type_: str
    source: AnimationEffect | None = ...
    css_id: str | None = ...
    view_or_scroll_timeline: ViewOrScrollTimeline | None = ...
    def to_json(self) -> T_JSON_DICT: ...
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> Animation: ...

@dataclass
class ViewOrScrollTimeline:
    axis: dom.ScrollOrientation
    source_node_id: dom.BackendNodeId | None = ...
    start_offset: float | None = ...
    end_offset: float | None = ...
    subject_node_id: dom.BackendNodeId | None = ...
    def to_json(self) -> T_JSON_DICT: ...
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> ViewOrScrollTimeline: ...

@dataclass
class AnimationEffect:
    delay: float
    end_delay: float
    iteration_start: float
    iterations: float
    duration: float
    direction: str
    fill: str
    easing: str
    backend_node_id: dom.BackendNodeId | None = ...
    keyframes_rule: KeyframesRule | None = ...
    def to_json(self) -> T_JSON_DICT: ...
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> AnimationEffect: ...

@dataclass
class KeyframesRule:
    keyframes: list[KeyframeStyle]
    name: str | None = ...
    def to_json(self) -> T_JSON_DICT: ...
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> KeyframesRule: ...

@dataclass
class KeyframeStyle:
    offset: str
    easing: str
    def to_json(self) -> T_JSON_DICT: ...
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> KeyframeStyle: ...

def disable() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]: ...
def enable() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]: ...
def get_current_time(id_: str) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, float]: ...
def get_playback_rate() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, float]: ...
def release_animations(animations: list[str]) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]: ...
def resolve_animation(animation_id: str) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, runtime.RemoteObject]: ...
def seek_animations(animations: list[str], current_time: float) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]: ...
def set_paused(animations: list[str], paused: bool) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]: ...
def set_playback_rate(playback_rate: float) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]: ...
def set_timing(animation_id: str, duration: float, delay: float) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]: ...

@dataclass
class AnimationCanceled:
    id_: str
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> AnimationCanceled: ...

@dataclass
class AnimationCreated:
    id_: str
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> AnimationCreated: ...

@dataclass
class AnimationStarted:
    animation: Animation
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> AnimationStarted: ...

@dataclass
class AnimationUpdated:
    animation: Animation
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> AnimationUpdated: ...
