import enum
import typing
from . import dom as dom, page as page
from .util import T_JSON_DICT as T_JSON_DICT, event_class as event_class
from dataclasses import dataclass

@dataclass
class CreditCard:
    number: str
    name: str
    expiry_month: str
    expiry_year: str
    cvc: str
    def to_json(self) -> T_JSON_DICT: ...
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> CreditCard: ...
    def __init__(self, number, name, expiry_month, expiry_year, cvc) -> None: ...

@dataclass
class AddressField:
    name: str
    value: str
    def to_json(self) -> T_JSON_DICT: ...
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> AddressField: ...
    def __init__(self, name, value) -> None: ...

@dataclass
class AddressFields:
    fields: typing.List[AddressField]
    def to_json(self) -> T_JSON_DICT: ...
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> AddressFields: ...
    def __init__(self, fields) -> None: ...

@dataclass
class Address:
    fields: typing.List[AddressField]
    def to_json(self) -> T_JSON_DICT: ...
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> Address: ...
    def __init__(self, fields) -> None: ...

@dataclass
class AddressUI:
    address_fields: typing.List[AddressFields]
    def to_json(self) -> T_JSON_DICT: ...
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> AddressUI: ...
    def __init__(self, address_fields) -> None: ...

class FillingStrategy(enum.Enum):
    AUTOCOMPLETE_ATTRIBUTE: str
    AUTOFILL_INFERRED: str
    def to_json(self) -> str: ...
    @classmethod
    def from_json(cls, json: str) -> FillingStrategy: ...

@dataclass
class FilledField:
    html_type: str
    id_: str
    name: str
    value: str
    autofill_type: str
    filling_strategy: FillingStrategy
    field_id: dom.BackendNodeId
    def to_json(self) -> T_JSON_DICT: ...
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> FilledField: ...
    def __init__(self, html_type, id_, name, value, autofill_type, filling_strategy, field_id) -> None: ...

def trigger(field_id: dom.BackendNodeId, card: CreditCard, frame_id: typing.Optional[page.FrameId] = None) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]: ...
def set_addresses(addresses: typing.List[Address]) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]: ...
def disable() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]: ...
def enable() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]: ...

@dataclass
class AddressFormFilled:
    filled_fields: typing.List[FilledField]
    address_ui: AddressUI
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> AddressFormFilled: ...
    def to_json(self) -> T_JSON_DICT: ...
    def __init__(self, filled_fields, address_ui) -> None: ...
