import enum
import typing
from . import storage as storage
from .util import T_JSON_DICT as T_JSON_DICT, event_class as event_class
from dataclasses import dataclass

class CacheId(str):
    def to_json(self) -> str: ...
    @classmethod
    def from_json(cls, json: str) -> CacheId: ...

class CachedResponseType(enum.Enum):
    BASIC: str
    CORS: str
    DEFAULT: str
    ERROR: str
    OPAQUE_RESPONSE: str
    OPAQUE_REDIRECT: str
    def to_json(self) -> str: ...
    @classmethod
    def from_json(cls, json: str) -> CachedResponseType: ...

@dataclass
class DataEntry:
    request_url: str
    request_method: str
    request_headers: typing.List[Header]
    response_time: float
    response_status: int
    response_status_text: str
    response_type: CachedResponseType
    response_headers: typing.List[Header]
    def to_json(self) -> T_JSON_DICT: ...
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> DataEntry: ...
    def __init__(self, request_url, request_method, request_headers, response_time, response_status, response_status_text, response_type, response_headers) -> None: ...

@dataclass
class Cache:
    cache_id: CacheId
    security_origin: str
    storage_key: str
    cache_name: str
    storage_bucket: typing.Optional[storage.StorageBucket] = ...
    def to_json(self) -> T_JSON_DICT: ...
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> Cache: ...
    def __init__(self, cache_id, security_origin, storage_key, cache_name, storage_bucket) -> None: ...

@dataclass
class Header:
    name: str
    value: str
    def to_json(self) -> T_JSON_DICT: ...
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> Header: ...
    def __init__(self, name, value) -> None: ...

@dataclass
class CachedResponse:
    body: str
    def to_json(self) -> T_JSON_DICT: ...
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> CachedResponse: ...
    def __init__(self, body) -> None: ...

def delete_cache(cache_id: CacheId) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]: ...
def delete_entry(cache_id: CacheId, request: str) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]: ...
def request_cache_names(security_origin: typing.Optional[str] = None, storage_key: typing.Optional[str] = None, storage_bucket: typing.Optional[storage.StorageBucket] = None) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, typing.List[Cache]]: ...
def request_cached_response(cache_id: CacheId, request_url: str, request_headers: typing.List[Header]) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, CachedResponse]: ...
def request_entries(cache_id: CacheId, skip_count: typing.Optional[int] = None, page_size: typing.Optional[int] = None, path_filter: typing.Optional[str] = None) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, typing.Tuple[typing.List[DataEntry], float]]: ...
