import typing
from .util import T_JSON_DICT as T_JSON_DICT, event_class as event_class
from dataclasses import dataclass as dataclass

def set_instrumentation_breakpoint(event_name: str) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]: ...
def remove_instrumentation_breakpoint(event_name: str) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]: ...
def disable() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]: ...
