import typing
from . import runtime as runtime
from .util import T_JSON_DICT as T_JSON_DICT, event_class as event_class
from dataclasses import dataclass

class HeapSnapshotObjectId(str):
    def to_json(self) -> str: ...
    @classmethod
    def from_json(cls, json: str) -> HeapSnapshotObjectId: ...

@dataclass
class SamplingHeapProfileNode:
    call_frame: runtime.CallFrame
    self_size: float
    id_: int
    children: list[SamplingHeapProfileNode]
    def to_json(self) -> T_JSON_DICT: ...
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> SamplingHeapProfileNode: ...

@dataclass
class SamplingHeapProfileSample:
    size: float
    node_id: int
    ordinal: float
    def to_json(self) -> T_JSON_DICT: ...
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> SamplingHeapProfileSample: ...

@dataclass
class SamplingHeapProfile:
    head: SamplingHeapProfileNode
    samples: list[SamplingHeapProfileSample]
    def to_json(self) -> T_JSON_DICT: ...
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> SamplingHeapProfile: ...

def add_inspected_heap_object(heap_object_id: HeapSnapshotObjectId) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]: ...
def collect_garbage() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]: ...
def disable() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]: ...
def enable() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]: ...
def get_heap_object_id(object_id: runtime.RemoteObjectId) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, HeapSnapshotObjectId]: ...
def get_object_by_heap_object_id(object_id: HeapSnapshotObjectId, object_group: str | None = None) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, runtime.RemoteObject]: ...
def get_sampling_profile() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, SamplingHeapProfile]: ...
def start_sampling(sampling_interval: float | None = None, include_objects_collected_by_major_gc: bool | None = None, include_objects_collected_by_minor_gc: bool | None = None) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]: ...
def start_tracking_heap_objects(track_allocations: bool | None = None) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]: ...
def stop_sampling() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, SamplingHeapProfile]: ...
def stop_tracking_heap_objects(report_progress: bool | None = None, treat_global_objects_as_roots: bool | None = None, capture_numeric_value: bool | None = None, expose_internals: bool | None = None) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]: ...
def take_heap_snapshot(report_progress: bool | None = None, treat_global_objects_as_roots: bool | None = None, capture_numeric_value: bool | None = None, expose_internals: bool | None = None) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]: ...

@dataclass
class AddHeapSnapshotChunk:
    chunk: str
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> AddHeapSnapshotChunk: ...

@dataclass
class HeapStatsUpdate:
    stats_update: list[int]
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> HeapStatsUpdate: ...

@dataclass
class LastSeenObjectId:
    last_seen_object_id: int
    timestamp: float
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> LastSeenObjectId: ...

@dataclass
class ReportHeapSnapshotProgress:
    done: int
    total: int
    finished: bool | None
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> ReportHeapSnapshotProgress: ...

@dataclass
class ResetProfiles:
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> ResetProfiles: ...
