import typing
from . import runtime as runtime, storage as storage
from .util import T_JSON_DICT as T_JSON_DICT, event_class as event_class
from dataclasses import dataclass

@dataclass
class DatabaseWithObjectStores:
    name: str
    version: float
    object_stores: list[ObjectStore]
    def to_json(self) -> T_JSON_DICT: ...
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> DatabaseWithObjectStores: ...

@dataclass
class ObjectStore:
    name: str
    key_path: KeyPath
    auto_increment: bool
    indexes: list[ObjectStoreIndex]
    def to_json(self) -> T_JSON_DICT: ...
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> ObjectStore: ...

@dataclass
class ObjectStoreIndex:
    name: str
    key_path: KeyPath
    unique: bool
    multi_entry: bool
    def to_json(self) -> T_JSON_DICT: ...
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> ObjectStoreIndex: ...

@dataclass
class Key:
    type_: str
    number: float | None = ...
    string: str | None = ...
    date: float | None = ...
    array: list[Key] | None = ...
    def to_json(self) -> T_JSON_DICT: ...
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> Key: ...

@dataclass
class KeyRange:
    lower_open: bool
    upper_open: bool
    lower: Key | None = ...
    upper: Key | None = ...
    def to_json(self) -> T_JSON_DICT: ...
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> KeyRange: ...

@dataclass
class DataEntry:
    key: runtime.RemoteObject
    primary_key: runtime.RemoteObject
    value: runtime.RemoteObject
    def to_json(self) -> T_JSON_DICT: ...
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> DataEntry: ...

@dataclass
class KeyPath:
    type_: str
    string: str | None = ...
    array: list[str] | None = ...
    def to_json(self) -> T_JSON_DICT: ...
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> KeyPath: ...

def clear_object_store(database_name: str, object_store_name: str, security_origin: str | None = None, storage_key: str | None = None, storage_bucket: storage.StorageBucket | None = None) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]: ...
def delete_database(database_name: str, security_origin: str | None = None, storage_key: str | None = None, storage_bucket: storage.StorageBucket | None = None) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]: ...
def delete_object_store_entries(database_name: str, object_store_name: str, key_range: KeyRange, security_origin: str | None = None, storage_key: str | None = None, storage_bucket: storage.StorageBucket | None = None) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]: ...
def disable() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]: ...
def enable() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]: ...
def request_data(database_name: str, object_store_name: str, index_name: str, skip_count: int, page_size: int, security_origin: str | None = None, storage_key: str | None = None, storage_bucket: storage.StorageBucket | None = None, key_range: KeyRange | None = None) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, tuple[list[DataEntry], bool]]: ...
def get_metadata(database_name: str, object_store_name: str, security_origin: str | None = None, storage_key: str | None = None, storage_bucket: storage.StorageBucket | None = None) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, tuple[float, float]]: ...
def request_database(database_name: str, security_origin: str | None = None, storage_key: str | None = None, storage_bucket: storage.StorageBucket | None = None) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, DatabaseWithObjectStores]: ...
def request_database_names(security_origin: str | None = None, storage_key: str | None = None, storage_bucket: storage.StorageBucket | None = None) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, list[str]]: ...
