import typing
from . import dom as dom
from .util import T_JSON_DICT as T_JSON_DICT, event_class as event_class
from dataclasses import dataclass

class LayerId(str):
    def to_json(self) -> str: ...
    @classmethod
    def from_json(cls, json: str) -> LayerId: ...

class SnapshotId(str):
    def to_json(self) -> str: ...
    @classmethod
    def from_json(cls, json: str) -> SnapshotId: ...

@dataclass
class ScrollRect:
    rect: dom.Rect
    type_: str
    def to_json(self) -> T_JSON_DICT: ...
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> ScrollRect: ...

@dataclass
class StickyPositionConstraint:
    sticky_box_rect: dom.Rect
    containing_block_rect: dom.Rect
    nearest_layer_shifting_sticky_box: LayerId | None = ...
    nearest_layer_shifting_containing_block: LayerId | None = ...
    def to_json(self) -> T_JSON_DICT: ...
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> StickyPositionConstraint: ...

@dataclass
class PictureTile:
    x: float
    y: float
    picture: str
    def to_json(self) -> T_JSON_DICT: ...
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> PictureTile: ...

@dataclass
class Layer:
    layer_id: LayerId
    offset_x: float
    offset_y: float
    width: float
    height: float
    paint_count: int
    draws_content: bool
    parent_layer_id: LayerId | None = ...
    backend_node_id: dom.BackendNodeId | None = ...
    transform: list[float] | None = ...
    anchor_x: float | None = ...
    anchor_y: float | None = ...
    anchor_z: float | None = ...
    invisible: bool | None = ...
    scroll_rects: list[ScrollRect] | None = ...
    sticky_position_constraint: StickyPositionConstraint | None = ...
    def to_json(self) -> T_JSON_DICT: ...
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> Layer: ...

class PaintProfile(list):
    def to_json(self) -> list[float]: ...
    @classmethod
    def from_json(cls, json: list[float]) -> PaintProfile: ...

def compositing_reasons(layer_id: LayerId) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, tuple[list[str], list[str]]]: ...
def disable() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]: ...
def enable() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]: ...
def load_snapshot(tiles: list[PictureTile]) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, SnapshotId]: ...
def make_snapshot(layer_id: LayerId) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, SnapshotId]: ...
def profile_snapshot(snapshot_id: SnapshotId, min_repeat_count: int | None = None, min_duration: float | None = None, clip_rect: dom.Rect | None = None) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, list[PaintProfile]]: ...
def release_snapshot(snapshot_id: SnapshotId) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]: ...
def replay_snapshot(snapshot_id: SnapshotId, from_step: int | None = None, to_step: int | None = None, scale: float | None = None) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, str]: ...
def snapshot_command_log(snapshot_id: SnapshotId) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, list[dict]]: ...

@dataclass
class LayerPainted:
    layer_id: LayerId
    clip: dom.Rect
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> LayerPainted: ...

@dataclass
class LayerTreeDidChange:
    layers: list[Layer] | None
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> LayerTreeDidChange: ...
