import typing
from . import dom as dom, network as network, page as page
from .util import T_JSON_DICT as T_JSON_DICT, event_class as event_class
from dataclasses import dataclass

@dataclass
class LargestContentfulPaint:
    render_time: network.TimeSinceEpoch
    load_time: network.TimeSinceEpoch
    size: float
    element_id: str | None = ...
    url: str | None = ...
    node_id: dom.BackendNodeId | None = ...
    def to_json(self) -> T_JSON_DICT: ...
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> LargestContentfulPaint: ...

@dataclass
class LayoutShiftAttribution:
    previous_rect: dom.Rect
    current_rect: dom.Rect
    node_id: dom.BackendNodeId | None = ...
    def to_json(self) -> T_JSON_DICT: ...
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> LayoutShiftAttribution: ...

@dataclass
class LayoutShift:
    value: float
    had_recent_input: bool
    last_input_time: network.TimeSinceEpoch
    sources: list[LayoutShiftAttribution]
    def to_json(self) -> T_JSON_DICT: ...
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> LayoutShift: ...

@dataclass
class TimelineEvent:
    frame_id: page.FrameId
    type_: str
    name: str
    time: network.TimeSinceEpoch
    duration: float | None = ...
    lcp_details: LargestContentfulPaint | None = ...
    layout_shift_details: LayoutShift | None = ...
    def to_json(self) -> T_JSON_DICT: ...
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> TimelineEvent: ...

def enable(event_types: list[str]) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]: ...

@dataclass
class TimelineEventAdded:
    event: TimelineEvent
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> TimelineEventAdded: ...
