import typing
from . import debugger as debugger, runtime as runtime
from .util import T_JSON_DICT as T_JSON_DICT, event_class as event_class
from dataclasses import dataclass

@dataclass
class ProfileNode:
    id_: int
    call_frame: runtime.CallFrame
    hit_count: int | None = ...
    children: list[int] | None = ...
    deopt_reason: str | None = ...
    position_ticks: list[PositionTickInfo] | None = ...
    def to_json(self) -> T_JSON_DICT: ...
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> ProfileNode: ...

@dataclass
class Profile:
    nodes: list[ProfileNode]
    start_time: float
    end_time: float
    samples: list[int] | None = ...
    time_deltas: list[int] | None = ...
    def to_json(self) -> T_JSON_DICT: ...
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> Profile: ...

@dataclass
class PositionTickInfo:
    line: int
    ticks: int
    def to_json(self) -> T_JSON_DICT: ...
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> PositionTickInfo: ...

@dataclass
class CoverageRange:
    start_offset: int
    end_offset: int
    count: int
    def to_json(self) -> T_JSON_DICT: ...
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> CoverageRange: ...

@dataclass
class FunctionCoverage:
    function_name: str
    ranges: list[CoverageRange]
    is_block_coverage: bool
    def to_json(self) -> T_JSON_DICT: ...
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> FunctionCoverage: ...

@dataclass
class ScriptCoverage:
    script_id: runtime.ScriptId
    url: str
    functions: list[FunctionCoverage]
    def to_json(self) -> T_JSON_DICT: ...
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> ScriptCoverage: ...

def disable() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]: ...
def enable() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]: ...
def get_best_effort_coverage() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, list[ScriptCoverage]]: ...
def set_sampling_interval(interval: int) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]: ...
def start() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]: ...
def start_precise_coverage(call_count: bool | None = None, detailed: bool | None = None, allow_triggered_updates: bool | None = None) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, float]: ...
def stop() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, Profile]: ...
def stop_precise_coverage() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]: ...
def take_precise_coverage() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, tuple[list[ScriptCoverage], float]]: ...

@dataclass
class ConsoleProfileFinished:
    id_: str
    location: debugger.Location
    profile: Profile
    title: str | None
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> ConsoleProfileFinished: ...

@dataclass
class ConsoleProfileStarted:
    id_: str
    location: debugger.Location
    title: str | None
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> ConsoleProfileStarted: ...

@dataclass
class PreciseCoverageDeltaUpdate:
    timestamp: float
    occasion: str
    result: list[ScriptCoverage]
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> PreciseCoverageDeltaUpdate: ...
