import enum
import typing
from . import browser as browser, page as page
from .util import T_JSON_DICT as T_JSON_DICT, event_class as event_class
from dataclasses import dataclass

class TargetID(str):
    def to_json(self) -> str: ...
    @classmethod
    def from_json(cls, json: str) -> TargetID: ...

class SessionID(str):
    def to_json(self) -> str: ...
    @classmethod
    def from_json(cls, json: str) -> SessionID: ...

@dataclass
class TargetInfo:
    target_id: TargetID
    type_: str
    title: str
    url: str
    attached: bool
    can_access_opener: bool
    opener_id: TargetID | None = ...
    opener_frame_id: page.FrameId | None = ...
    browser_context_id: browser.BrowserContextID | None = ...
    subtype: str | None = ...
    def to_json(self) -> T_JSON_DICT: ...
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> TargetInfo: ...

@dataclass
class FilterEntry:
    exclude: bool | None = ...
    type_: str | None = ...
    def to_json(self) -> T_JSON_DICT: ...
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> FilterEntry: ...

class TargetFilter(list):
    def to_json(self) -> list[FilterEntry]: ...
    @classmethod
    def from_json(cls, json: list[FilterEntry]) -> TargetFilter: ...

@dataclass
class RemoteLocation:
    host: str
    port: int
    def to_json(self) -> T_JSON_DICT: ...
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> RemoteLocation: ...

class WindowState(enum.Enum):
    NORMAL = 'normal'
    MINIMIZED = 'minimized'
    MAXIMIZED = 'maximized'
    FULLSCREEN = 'fullscreen'
    def to_json(self) -> str: ...
    @classmethod
    def from_json(cls, json: str) -> WindowState: ...

def activate_target(target_id: TargetID) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]: ...
def attach_to_target(target_id: TargetID, flatten: bool | None = None) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, SessionID]: ...
def attach_to_browser_target() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, SessionID]: ...
def close_target(target_id: TargetID) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, bool]: ...
def expose_dev_tools_protocol(target_id: TargetID, binding_name: str | None = None, inherit_permissions: bool | None = None) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]: ...
def create_browser_context(dispose_on_detach: bool | None = None, proxy_server: str | None = None, proxy_bypass_list: str | None = None, origins_with_universal_network_access: list[str] | None = None) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, browser.BrowserContextID]: ...
def get_browser_contexts() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, list[browser.BrowserContextID]]: ...
def create_target(url: str, left: int | None = None, top: int | None = None, width: int | None = None, height: int | None = None, window_state: WindowState | None = None, browser_context_id: browser.BrowserContextID | None = None, enable_begin_frame_control: bool | None = None, new_window: bool | None = None, background: bool | None = None, for_tab: bool | None = None) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, TargetID]: ...
def detach_from_target(session_id: SessionID | None = None, target_id: TargetID | None = None) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]: ...
def dispose_browser_context(browser_context_id: browser.BrowserContextID) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]: ...
def get_target_info(target_id: TargetID | None = None) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, TargetInfo]: ...
def get_targets(filter_: TargetFilter | None = None) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, list[TargetInfo]]: ...
def send_message_to_target(message: str, session_id: SessionID | None = None, target_id: TargetID | None = None) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]: ...
def set_auto_attach(auto_attach: bool, wait_for_debugger_on_start: bool, flatten: bool | None = None, filter_: TargetFilter | None = None) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]: ...
def auto_attach_related(target_id: TargetID, wait_for_debugger_on_start: bool, filter_: TargetFilter | None = None) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]: ...
def set_discover_targets(discover: bool, filter_: TargetFilter | None = None) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]: ...
def set_remote_locations(locations: list[RemoteLocation]) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]: ...

@dataclass
class AttachedToTarget:
    session_id: SessionID
    target_info: TargetInfo
    waiting_for_debugger: bool
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> AttachedToTarget: ...

@dataclass
class DetachedFromTarget:
    session_id: SessionID
    target_id: TargetID | None
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> DetachedFromTarget: ...

@dataclass
class ReceivedMessageFromTarget:
    session_id: SessionID
    message: str
    target_id: TargetID | None
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> ReceivedMessageFromTarget: ...

@dataclass
class TargetCreated:
    target_info: TargetInfo
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> TargetCreated: ...

@dataclass
class TargetDestroyed:
    target_id: TargetID
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> TargetDestroyed: ...

@dataclass
class TargetCrashed:
    target_id: TargetID
    status: str
    error_code: int
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> TargetCrashed: ...

@dataclass
class TargetInfoChanged:
    target_info: TargetInfo
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> TargetInfoChanged: ...
