import typing
from _typeshed import Incomplete

T_JSON_DICT = dict[str, typing.Any]

class UnknownObject:
    def __init__(self, elements: dict) -> None: ...
    def __getattr__(self, name): ...
    @classmethod
    def from_json(cls, json: T_JSON_DICT): ...

class UnknownEvent(UnknownObject):
    name: Incomplete
    def __init__(self, name, elements) -> None: ...
    @classmethod
    def from_json(cls, json: T_JSON_DICT): ...

def event_class(method): ...
def parse_json_event(json: T_JSON_DICT) -> typing.Any: ...
