import asyncio
from autobahn.wamp.types import TransportDetails as TransportDetails
from typing import Optional

def transport_channel_id(transport, is_server: bool, channel_id_type: Optional[str] = None) -> bytes: ...
def peer2str(transport: asyncio.transports.BaseTransport) -> str: ...
def get_serializers(): ...
def create_transport_details(transport, is_server: bool) -> TransportDetails: ...
