from _typeshed import Incomplete
from wsaccel.xormask import XorMaskerNull as XorMaskerNull, createXorMasker

create_xor_masker = createXorMasker
xrange = range

class XorMaskerNull:
    def __init__(self, mask: Incomplete | None = None) -> None: ...
    def pointer(self): ...
    def reset(self) -> None: ...
    def process(self, data): ...

class XorMaskerSimple:
    def __init__(self, mask) -> None: ...
    def pointer(self): ...
    def reset(self) -> None: ...
    def process(self, data): ...

class XorMaskerShifted1:
    def __init__(self, mask) -> None: ...
    def pointer(self): ...
    def reset(self) -> None: ...
    def process(self, data): ...
