from pycdp.utils import LoggerMixin as LoggerMixin

class BrowserLauncher(LoggerMixin):
    def __init__(self, *, binary: str, profile: str = None, keep_profile: bool = True, headless: bool = False, locale: str = None, timezone: str = None, proxy: str = None, window_width: int = None, window_height: int = None, initial_url: str = None, extensions: list[str] = [], args: list[str] = None, log: bool = True) -> None: ...
    @property
    def pid(self) -> int: ...
    @property
    def locale(self): ...
    @property
    def timezone(self): ...
    def launch(self) -> None: ...
    def kill(self, timeout: float = 3.0): ...
    def __del__(self) -> None: ...

class ChromeLauncher(BrowserLauncher): ...
