from _typeshed import Incomplete

class CDPError(Exception): ...

class CDPBrowserError(CDPError):
    code: int
    message: str
    detail: Incomplete
    def __init__(self, obj) -> None: ...

class CDPConnectionClosed(CDPError):
    reason: Incomplete
    def __init__(self, reason) -> None: ...

class CDPSessionClosed(CDPError): ...
class CDPInternalError(CDPError): ...
class CDPEventListenerClosed(CDPError): ...
