import typing
from .util import T_JSON_DICT as T_JSON_DICT, event_class as event_class
from dataclasses import dataclass

class SerializedStorageKey(str):
    def to_json(self) -> str: ...
    @classmethod
    def from_json(cls, json: str) -> SerializedStorageKey: ...

@dataclass
class StorageId:
    is_local_storage: bool
    security_origin: typing.Optional[str] = ...
    storage_key: typing.Optional[SerializedStorageKey] = ...
    def to_json(self) -> T_JSON_DICT: ...
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> StorageId: ...
    def __init__(self, is_local_storage, security_origin, storage_key) -> None: ...

class Item(list):
    def to_json(self) -> typing.List[str]: ...
    @classmethod
    def from_json(cls, json: typing.List[str]) -> Item: ...

def clear(storage_id: StorageId) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]: ...
def disable() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]: ...
def enable() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]: ...
def get_dom_storage_items(storage_id: StorageId) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, typing.List[Item]]: ...
def remove_dom_storage_item(storage_id: StorageId, key: str) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]: ...
def set_dom_storage_item(storage_id: StorageId, key: str, value: str) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]: ...

@dataclass
class DomStorageItemAdded:
    storage_id: StorageId
    key: str
    new_value: str
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> DomStorageItemAdded: ...
    def to_json(self) -> T_JSON_DICT: ...
    def __init__(self, storage_id, key, new_value) -> None: ...

@dataclass
class DomStorageItemRemoved:
    storage_id: StorageId
    key: str
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> DomStorageItemRemoved: ...
    def to_json(self) -> T_JSON_DICT: ...
    def __init__(self, storage_id, key) -> None: ...

@dataclass
class DomStorageItemUpdated:
    storage_id: StorageId
    key: str
    old_value: str
    new_value: str
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> DomStorageItemUpdated: ...
    def to_json(self) -> T_JSON_DICT: ...
    def __init__(self, storage_id, key, old_value, new_value) -> None: ...

@dataclass
class DomStorageItemsCleared:
    storage_id: StorageId
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> DomStorageItemsCleared: ...
    def to_json(self) -> T_JSON_DICT: ...
    def __init__(self, storage_id) -> None: ...
