name: pytest

on: [push]

permissions:
  contents: write

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-${{ hashFiles('requirements.txt', 'dev/requirements-dev.txt') }}
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Upgrade pip
      run: python -m pip install --upgrade pip
    - name: Install package dependencies
      run: |
        python -m pip install -r requirements.txt
    - name: Install dev dependencies
      run: python -m pip install -r dev/requirements-dev.txt
    - name: Run all the python checks
      run: ./dev/check.sh pytest
    - name: Archive code coverage results
      uses: actions/upload-artifact@v4
      with:
        name: python_coverage
        path: .coverage
  upload-badge:
    runs-on: ubuntu-latest
    needs: check
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Upgrade pip and install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install coverage-badge
      - name: Download coverage file
        uses: actions/download-artifact@v4
        with:
          name: python_coverage
      - name: Generate coverage badge
        run: coverage-badge -f -o dev/coverage-badge.svg
      - name: Upload coverage badge
        uses: EndBug/add-and-commit@v9
        with:
          add: 'dev/coverage-badge.svg'
          author_name: Razvan Pricop
          author_email: 22615594+RazorBest@users.noreply.github.com
          commit: --signoff
          message: 'Upload coverage percentage badge'
